#!/usr/bin/env python3
"""Merge per-track topic simulator specs into src/components/training/simulationMasterData.ts"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sim_track_1 import TRACK as T1
from sim_track_2 import TRACK as T2
from sim_track_3 import TRACK as T3

merged = {}
for t in (T1, T2, T3):
    for k, v in t.items():
        merged[k] = v

# normalize osint items to {label, risk}
for spec in merged.values():
    if 'osint_items' in spec:
        spec['osint_items'] = [{k: v for k, v in it.items() if k in ('label', 'risk')} for it in spec['osint_items']]

# Build a title -> code map from the course catalog so getTopicSimulation can
# resolve the right simulator even when an entry point lacks the course code.
base = os.path.dirname(os.path.abspath(__file__))
import re
src_path = os.path.join(base, '..', 'server', 'database', 'trainingMasterData.ts')
with open(src_path, encoding='utf-8') as f:
    src = f.read()
pairs = re.findall(r"code: '(COURSE-[^']+)',\s*title: '([^']+)'", src)
title_to_code = {}
for code, title in pairs:
    title_to_code[title] = code
print('entries:', len(merged), '| title map:', len(title_to_code))

HEADER = '''// AUTO-GENERATED by scripts/generate_simulation_file.py — do not edit by hand.
// Topic-specific Live Interactive Threat Demo Simulator specs for all 120 masterclass courses.

export type SimArchetype =
  | 'email' | 'headers' | 'url' | 'attachment' | 'bec' | 'oauth' | 'mfa' | 'qr'
  | 'sms' | 'voice' | 'video' | 'psychology' | 'ai' | 'ir' | 'portal' | 'physical'
  | 'perimeter' | 'osint';

export interface TopicSimulationSpec {
  sim_type: SimArchetype;
  sim_label: string;
  // email / headers
  sender_name?: string;
  sender_email?: string;
  return_path?: string;
  reply_to?: string;
  subject?: string;
  headline?: string;
  body?: string;
  button_text?: string;
  hover_url?: string;
  display_name?: string;
  from_email?: string;
  auth_results?: string;
  // url
  fake_subdomain?: string;
  root_domain?: string;
  url_path?: string;
  url_note_1?: string;
  url_note_2?: string;
  // attachment
  filename?: string;
  lure_text?: string;
  table_title?: string;
  table_rows?: string[][];
  // bec
  vendor_original?: string[];
  vendor_forged?: string[];
  // oauth
  app_name?: string;
  publisher_note?: string;
  scopes?: Array<{ name: string; desc: string; level: 'warn' | 'crit' }>;
  // mfa
  push_count?: number;
  push_text?: string;
  mfa_note?: string;
  // qr
  decoded_url?: string;
  qr_context?: string;
  // sms
  sms_sender?: string;
  sms_phone?: string;
  sms_message?: string;
  sms_link?: string;
  // voice
  caller_id?: string;
  caller_phone?: string;
  call_script?: string;
  safe_response?: string;
  risky_response?: string;
  // video
  video_caller?: string;
  video_artifacts?: string[];
  // psychology
  psych_lure?: string;
  psych_answer?: string;
  // ai
  ai_doc?: string;
  ai_visible?: string;
  ai_injection?: string;
  // ir
  ir_steps?: Array<{ title: string; detail: string }>;
  // portal
  portal_brand?: string;
  portal_headline?: string;
  portal_sub?: string;
  portal_button?: string;
  portal_url?: string;
  // physical
  phys_scenario?: string;
  phys_safe?: string;
  phys_risky?: string;
  // perimeter
  perimeter_cards?: Array<{ title: string; desc: string; stat: string }>;
  // osint
  profile_name?: string;
  osint_items?: Array<{ label: string; risk: string }>;
}

export const allTopicSimulations: Record<string, TopicSimulationSpec> = '''

FOOTER = '''

const titleToCode: Record<string, string> = __TITLE_MAP__;

/** Resolve the topic-specific simulator for a course. Falls back to a generic
 *  credential-phish email spec keyed on the course title when no code matches. */
export const getTopicSimulation = (code?: string, title?: string, category?: string): TopicSimulationSpec => {
  const key = (code || '').toUpperCase();
  if (key && allTopicSimulations[key]) return allTopicSimulations[key];
  const mapped = titleToCode[title || ''] || titleToCode[(title || '').replace(/^[^\\w]+/, '').trim()];
  if (mapped && allTopicSimulations[mapped]) return allTopicSimulations[mapped];
  const t = (title || 'Cybersecurity Defense').replace(/^[^\\w]+/, '');
  return {
    sim_type: 'email',
    sim_label: 'Credential-Phish Email Simulator',
    sender_name: 'Corporate Security Operations',
    sender_email: 'alerts@company-security-verify.net',
    return_path: 'bounce@external-relay-cloud.net',
    subject: `Action Required: ${t}`,
    headline: `Action Required: ${t}`,
    body: 'Your corporate session credentials have expired. Failure to authenticate within 15 minutes will result in immediate mailbox lockout.',
    button_text: 'Verify Corporate Session Now',
    hover_url: 'https://login.company.security-auth-check.org/v2'
  };
};
'''

body = json.dumps(merged, indent=1, ensure_ascii=False)
titlemap = json.dumps(title_to_code, ensure_ascii=False)
out = HEADER + body + ';\n' + FOOTER.replace('__TITLE_MAP__', titlemap)
dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'components', 'training', 'simulationMasterData.ts')
with open(dest, 'w', encoding='utf-8') as f:
    f.write(out)
print('wrote', dest, os.path.getsize(dest), 'bytes')
