# Topic-specific Live Threat Simulator specs — Courses 01-40
TRACK = {
 'COURSE-01-CYBER-BASICS': dict(sim_type='perimeter', sim_label='Enterprise Attack Surface Entry-Point Simulator',
  perimeter_cards=[
   dict(title='1. Spearphish Email Lure', desc='Fake "session expired" mail targeting new hires on day one.', stat='91% Common'),
   dict(title='2. Smishing Fraud Alert', desc='Bank lockdown text aimed at personal mobiles, bypassing the email gateway.', stat='Mobile Bypass'),
   dict(title='3. Vishing Helpdesk Call', desc='Caller posing as senior IT demands your 6-digit MFA code.', stat='AI Audio'),
   dict(title='4. Macro Attachment', desc='Payroll_Bonus.xlsm with an "Enable Content" decryption lure.', stat='Macro Lure')]),
 'COURSE-02-PHISHING-INTRO': dict(sim_type='email', sim_label='Classic Credential-Harvest Spearphish Simulator',
  sender_name='Corporate Security Operations', sender_email='alerts@company-security-verify.net', return_path='bounce@external-relay-cloud.net',
  subject='Action Required: Verify Session to Avoid Account Suspension',
  headline='Action Required: Verify Session to Avoid Account Suspension',
  body='Your corporate session credentials have expired. Failure to authenticate within 15 minutes will result in immediate mailbox lockout.',
  button_text='Verify Corporate Session Now', hover_url='https://login.company.security-auth-check.org/v2'),
 'COURSE-03-TARGET-EMPLOYEE': dict(sim_type='psychology', sim_label='Human Attack Surface Targeting Classifier',
  psych_lure='An attacker reads your LinkedIn post about joining the finance team, then emails you as "HR Payroll" with a "welcome bonus enrollment form" asking for your bank routing and SSN. What made you the target?',
  psych_answer='Your public oversharing built a targeted pretext — the "bonus form" harvests banking details and PII, not a reward.'),
 'COURSE-04-SOCIAL-ENGINEERING': dict(sim_type='psychology', sim_label='Manipulation & Trust Exploitation Classifier',
  psych_lure='"Hi, I just joined IT. My manager said you would help me — can you approve this MFA push so I can finish my setup?" Which manipulation lever is being pulled?',
  psych_answer='Helpfulness and coworker trust (reciprocity + social proof). No technical exploit is needed — just your willingness to assist.'),
 'COURSE-05-HUMAN-PSYCHOLOGY': dict(sim_type='psychology', sim_label='Fear, Greed & Authority Trigger Laboratory',
  psych_lure='"FINAL NOTICE: Your gym membership lawsuit settlement of $2,400 must be claimed today or is forfeited forever." Which two levers combine here?',
  psych_answer='Greed/reward fused with artificial urgency — the claim portal then asks for your card details to "deposit" the money.'),
 'COURSE-06-CYBER-ATTACK-TYPES': dict(sim_type='perimeter', sim_label='Attack-Type Comparison Range (Phish / Ransom / MITM / QR)',
  perimeter_cards=[
   dict(title='1. Phishing Email', desc='Lookalike M365 portal harvesting credentials.', stat='Initial Access'),
   dict(title='2. Ransomware Macro', desc='Invoice.docm executes PowerShell encryptor.', stat='Payload'),
   dict(title='3. MITM Evil Twin', desc='Rogue AP relays your SSO session live.', stat='Network'),
   dict(title='4. QR Quishing', desc='Poster QR routes phones to fake MFA page.', stat='Mobile')]),
 'COURSE-07-AWARENESS-FUNDAMENTALS': dict(sim_type='ir', sim_label='Defense-in-Depth Daily Runbook Simulator',
  ir_steps=[
   dict(title='Verify Before Acting', detail='Open a fresh tab and use bookmarked portals for any account notice.'),
   dict(title='Report, Do Not Forward', detail='Use the 1-click Report Phishing button so SOC gets full headers.'),
   dict(title='Patch & Update', detail='Same-day browser/OS updates close the exploit chain.'),
   dict(title='Phishing-Resistant MFA', detail='Enroll FIDO2 keys so harvested passwords are useless.')]),
 'COURSE-08-ORGANIZATIONAL-ROLE': dict(sim_type='ir', sim_label='Human Firewall First-Responder Drill',
  ir_steps=[
   dict(title='Spot the Anomaly', detail='Unexpected urgency, odd reply-to, or unknown root domain = stop.'),
   dict(title='Do Not Click or Reply', detail='Interaction confirms to attackers that your mailbox is live.'),
   dict(title='Report Within 60 Seconds', detail='Your report triggers fleet-wide purge of the same lure.'),
   dict(title='Preserve Evidence', detail='Keep the original message; do not delete until SOC confirms.')]),
 'COURSE-09-WHAT-ATTACKERS-WANT': dict(sim_type='psychology', sim_label='Data-Theft Objective Classifier',
  psych_lure='A "wellness survey" promises a $50 gift card but asks for your SSN, date of birth, and bank routing number. What is the attacker actually collecting?',
  psych_answer='Credentials, PII, and banking data for identity fraud and account takeover — the gift card is bait, not the goal.'),
 'COURSE-10-RECOGNIZING-SUSPICIOUS': dict(sim_type='psychology', sim_label='The Instinct Test: Gut-Feel Red Flag Trainer',
  psych_lure='A vendor email uses your full name, but the Reply-To is a free mailbox and it insists "this must be settled today only." Your gut says off. What confirms it?',
  psych_answer='Trust the instinct, then verify out-of-band: the mismatched Reply-To and same-day pressure are textbook coercion signals.'),
 'COURSE-11-EMAIL-ANATOMY': dict(sim_type='headers', sim_label='Phishing Email Anatomy & Header Dissection Lab',
  display_name='IT Service Desk', from_email='support@corp-it-portal.net', return_path='bounces@bulk-sender-relay.io',
  reply_to='harvest-desk@proton.me', auth_results='spf=fail (unauthorized IP) dkim=none dmarc=fail'),
 'COURSE-12-INSPECT-SENDER': dict(sim_type='headers', sim_label='Sender Spoofing & Display-Name Detection Lab',
  display_name='Victoria Sterling (CEO)', from_email='ceo-office@external-relay-gateway.net', return_path='attacker-bounce@money-harvest.ru',
  reply_to='executive-confidential@external-drop.io', auth_results='spf=fail (IP 194.26.29.11 unauthorized) dkim=invalid'),
 'COURSE-13-CHECK-DOMAINS': dict(sim_type='headers', sim_label='SPF / DKIM / DMARC Authentication Forensics Lab',
  display_name='Microsoft 365 Security', from_email='no-reply@microsoft365-alerts.com', return_path='bounce@campaign-blaster.net',
  reply_to='bounce@campaign-blaster.net', auth_results='spf=softfail dkim=fail (selector mismatch) dmarc=fail (policy=reject)'),
 'COURSE-14-SUSPICIOUS-LINKS': dict(sim_type='url', sim_label='Open-Redirect & Hidden Destination Link Lab',
  fake_subdomain='portal.yourcompany.com.', root_domain='link-redirect-hub.net', url_path='/r/?u=a8f3e2',
  url_note_1='The trusted-looking prefix is just a subdomain of the attacker hub; an open redirect hops you onward.',
  url_note_2='Short tracking parameters mask the final destination — always expand redirects before trusting.'),
 'COURSE-15-URL-INSPECTION': dict(sim_type='url', sim_label='Subdomain vs Root Domain Inspection Lab',
  fake_subdomain='login.microsoftonline.com.', root_domain='security-auth-check.org', url_path='/auth/v2?session=expired',
  url_note_1='"login.microsoftonline.com" here is only a subdomain prefix engineered to trigger familiarity bias.',
  url_note_2='The controlling root domain — security-auth-check.org — owns the server, the TLS cert, and your credentials.'),
 'COURSE-16-LOOKALIKE-DOMAINS': dict(sim_type='url', sim_label='IDN Homograph & Lookalike Character Laboratory',
  fake_subdomain='accounts.', root_domain='googłe.com (Cyrillic "ł")', url_path='/signin/v3',
  url_note_1='One substituted Unicode character makes the domain visually identical to the real brand.',
  url_note_2='Browsers may render punycode (xn--...) — treat any punycode brand domain as hostile.'),
 'COURSE-17-TYPOSQUATTING': dict(sim_type='url', sim_label='Typosquat & Combosquat Detection Range',
  fake_subdomain='support.', root_domain='mcirosoft-365-login.com', url_path='/passwordreset',
  url_note_1='Transposed letters ("mcirosoft") exploit hurried reading; combosquatting appends "-365-login" for context.',
  url_note_2='Only microsoft.com root domains are legitimate — extra keywords in the root are a hostile signal.'),
 'COURSE-18-URGENCY-FEAR': dict(sim_type='psychology', sim_label='24-Hour Deadline Pressure Analyzer',
  psych_lure='"Your mailbox will be permanently deleted in 2 hours unless you re-validate your credentials now." Why does the attacker impose a countdown?',
  psych_answer='Panic short-circuits analytical verification — victims click before consulting IT or inspecting the domain.'),
 'COURSE-19-FAKE-ACCOUNT-ALERTS': dict(sim_type='email', sim_label='False "Password Expired" Alert Simulator',
  sender_name='Identity Protection Team', sender_email='expire@password-keep-current.net', return_path='bounce@alert-farm-77.io',
  subject='Password Expiry Warning: Keep Your Current Password',
  headline='Your password expires today — click below to keep your current password',
  body='Our records show your corporate password reaches maximum age at 5:00 PM. Use the secure link to retain your current password and avoid reset procedures.',
  button_text='Keep Current Password', hover_url='https://identity.company.com.keep-current-pw.net'),
 'COURSE-20-PASSWORD-EXPIRATION': dict(sim_type='email', sim_label='"Keep Current Password" Trap Simulator',
  sender_name='HR Benefits & Identity', sender_email='identity@hr-password-rotation.net', return_path='bounce@rotation-blast-3.net',
  subject='Mandatory Password Rotation — Retain Option Available',
  headline='Rotation due: retain your existing password with one click',
  body='To reduce helpdesk load, employees may now retain their existing password by confirming it through the verification portal below.',
  button_text='Confirm & Retain Password', hover_url='https://portal.company.com.pw-retain-check.org'),
 'COURSE-21-FAKE-M365-NOTICES': dict(sim_type='email', sim_label='Spoofed OneDrive Quota Notification Simulator',
  sender_name='Microsoft 365', sender_email='no-reply@office-quota-alert.net', return_path='bounce@quota-campaign-9.io',
  subject='OneDrive is 98% full — files will be deleted in 24 hours',
  headline='Storage limit reached: release space to keep your files',
  body='Your OneDrive for Business has exceeded its quota. Unreleased files older than 90 days will be permanently purged unless you act now.',
  button_text='Release Storage Space', hover_url='https://onedrive.microsoft.com.storage-quota-fix.net'),
 'COURSE-22-FAKE-HR-EMAILS': dict(sim_type='email', sim_label='HR Benefits Audit SSN-Harvest Simulator',
  sender_name='Human Resources', sender_email='hr@benefits-enrollment-portal.net', return_path='bounce@hr-blast-22.net',
  subject='Open Enrollment: Confirm SSN & Banking for Benefits Audit',
  headline='Benefits audit: re-submit your SSN and direct deposit details',
  body='To avoid a lapse in coverage, complete the external enrollment spreadsheet with your Social Security Number, DOB, and bank account before Friday.',
  button_text='Submit Employee Data', hover_url='https://hr.company.com.benefits-audit-form.org'),
 'COURSE-23-FAKE-PAYROLL-EMAILS': dict(sim_type='bec', sim_label='Direct-Deposit Diversion Comparison Lab',
  vendor_original=['Employee: David Harrison', 'Bank: First National Credit Union', 'Routing: 211377137 (on file 3 yrs)', 'Account: ****8819'],
  vendor_forged=['Employee: David Harrison', 'Bank: Prepaid Reloadable Account', 'Routing: 111000994 (NEW)', 'Account: ****4192 (NEW)']),
 'COURSE-24-FAKE-INVOICES': dict(sim_type='bec', sim_label='Vendor Impersonation & Wire Routing Fraud Lab',
  vendor_original=['Vendor: Apex Consulting LLC', 'Bank: Chase Commercial Treasury', 'Routing: 021000021', 'Account: ****8819'],
  vendor_forged=['Vendor: Apex Consu1ting LLC', 'Bank: Offshore Escrow Vault', 'Routing: 091000994 (NEW)', 'Account: ****4192 (NEW)']),
 'COURSE-25-FAKE-DELIVERY-NOTICES': dict(sim_type='email', sim_label='Courier Parcel-Hold Phishing Simulator',
  sender_name='FedEx Delivery', sender_email='noreply@fedex-parcel-hold.net', return_path='bounce@courier-blast-5.io',
  subject='Parcel On Hold: Missing Address Information',
  headline='We attempted a delivery — schedule redelivery within 12 hours',
  body='Your package could not be delivered due to an incomplete street address. Pay the $1.99 redelivery fee and confirm your address to release the parcel.',
  button_text='Schedule Redelivery', hover_url='https://fedex.com.parcel-hold-redelivery.net'),
 'COURSE-26-EXECUTIVE-IMPERSONATION': dict(sim_type='email', sim_label='CEO Fraud & Urgent Wire Lure Simulator',
  sender_name='David Harrison (CEO)', sender_email='ceo@company-board-urgent.net', return_path='bounce@exec-spoof-1.ru',
  subject='Urgent: Confidential Acquisition Wire — Handle Personally',
  headline='I am in a board meeting. Release the acquisition wire now.',
  body='This is time-critical and must stay confidential. Review the wire details and confirm once released. Do not discuss with the finance team until announced.',
  button_text='Review Wire Details', hover_url='https://board.company.com.urgent-wire-approval.org'),
 'COURSE-27-BEC-AWARENESS': dict(sim_type='bec', sim_label='BEC Thread-Landscape Invoice Comparison Lab',
  vendor_original=['Vendor: Global Logistics Partners', 'Bank: Wells Fargo Commercial', 'Routing: 121000248', 'Account: ****3307'],
  vendor_forged=['Vendor: Global Logistics Partnars', 'Bank: Eastern Trust Holdings', 'Routing: 026009593 (CHANGED)', 'Account: ****9911 (CHANGED)']),
 'COURSE-28-SUSPICIOUS-ATTACHMENTS': dict(sim_type='attachment', sim_label='Double-Extension Executable Attachment Lab',
  filename='Q3_Invoice_Summary.pdf.exe', lure_text='Windows hides known extensions by default — this is an executable, not a PDF. Opening it runs attacker code instantly.',
  table_title='Invoice lines (rendered only after "Enable")', table_rows=[['INV-2201', 'Consulting', '$18,400.00'], ['INV-2202', 'Logistics', '$9,150.00']]),
 'COURSE-29-DANGEROUS-DOCUMENT-TYPES': dict(sim_type='attachment', sim_label='.xlsm / .pdf.exe / .iso Danger Format Lab',
  filename='Payroll_Extract_August.iso', lure_text='Disk images (.iso) bypass mail gateway AV and auto-mount with executable payloads inside — a favorite ransomware delivery container.',
  table_title='Container contents (hidden until mounted)', table_rows=[['setup.exe', 'Autorun', 'Mount-triggered'], ['invoice.pdf.lnk', 'Shortcut', 'Runs PowerShell']]),
 'COURSE-30-QR-QUISHING': dict(sim_type='qr', sim_label='Quishing Camera Viewfinder & MFA Hijack Lab',
  decoded_url='https://m365-authenticator-sync.auth-relay-gate.com/qr/v2',
  qr_context='QR code embedded in a PDF emailed as "MFA re-enrollment instructions" — scanning routes your phone to a fake MFA portal.'),
 'COURSE-31-MALICIOUS-DOCS': dict(sim_type='attachment', sim_label='VBA Macro & Obfuscation Mechanics Lab',
  filename='Salary_Adjustments.xlsm', lure_text='AutoOpen VBA decodes an obfuscated PowerShell downloader straight into memory — no file ever touches disk.',
  table_title='Blurred payroll preview (macro-gated)', table_rows=[['Executive', 'Adjustment', '+$42,000'], ['[48 rows hidden]', 'requires VBA', '—']]),
 'COURSE-32-OFFICE-ATTACHMENTS': dict(sim_type='attachment', sim_label='The "Enable Content" Social Trap Lab',
  filename='Bonus_Remuneration.xlsm', lure_text='The document claims salary data is "encrypted" until you click Enable Content — macros are never required to view a spreadsheet.',
  table_title='Executive bonus preview (blurred)', table_rows=[['David Harrison', 'Executive', '$125,000.00'], ['[48 rows]', 'macros required', '—']]),
 'COURSE-33-MACRO-AWARENESS': dict(sim_type='attachment', sim_label='Why Legitimate Docs Never Need VBA Lab',
  filename='Vendor_Contract_Template.docm', lure_text='Legal templates distribute as .pdf or .docx. A macro-enabled .docm from an external sender is hostile until proven otherwise.',
  table_title='Contract clauses (locked by macro banner)', table_rows=[['§4 Liability', 'capped', 'see macro'], ['§7 Payment', 'NET-30', 'see macro']]),
 'COURSE-34-UNEXPECTED-PDFS': dict(sim_type='attachment', sim_label='Embedded PDF Link & Form Harvest Lab',
  filename='eStatement_August.pdf', lure_text='The PDF renders fine, but its "Update card details" form posts to a lookalike bank host — PDFs can carry live hyperlinks and form fields.',
  table_title='Statement summary', table_rows=[['Opening', '$4,210.55', ''], ['Card verification', 'REQUIRED', 'click form']]),
 'COURSE-35-DANGEROUS-EXTENSIONS': dict(sim_type='attachment', sim_label='Double-Extension & Hidden Suffix Lab',
  filename='Meeting_Notes.txt.scr', lure_text='A Windows screensaver executable wearing a .txt costume. Enable "File name extensions" in Explorer to expose the true suffix.',
  table_title='Extension risk matrix', table_rows=[['.scr / .exe / .vbs', 'executes code', 'BLOCK'], ['.iso / .img', 'mounts payloads', 'BLOCK']]),
 'COURSE-36-SAFE-DOWNLOADS': dict(sim_type='attachment', sim_label='Hash Verification & Sandbox Download Lab',
  filename='VPN_Client_Setup.iso', lure_text='Unsolicited "installer" from a forum mirror. Compare publisher hashes, scan in a sandbox, and prefer the vendor\'s signed root domain.',
  table_title='Integrity check', table_rows=[['Expected SHA256', '9f2c…aa10', 'vendor-signed'], ['Download SHA256', 'e771…00b3', 'MISMATCH']]),
 'COURSE-37-FAKE-SHARED-DOCS': dict(sim_type='portal', sim_label='Fake Drive Share → SSO Harvest Portal',
  portal_brand='Google Drive', portal_headline='david.harrison shared "Q3_Bonus_Matrix.xlsx" with you',
  portal_sub='Sign in with your corporate account to view the document.', portal_button='Open Document',
  portal_url='https://drive.google.com.doc-share-view.net'),
 'COURSE-38-CLOUD-STORAGE-PHISH': dict(sim_type='portal', sim_label='Evilginx Cloud Storage SSO Trap Lab',
  portal_brand='Dropbox Business', portal_headline='Secure file drop from your external auditor',
  portal_sub='The relay proxies your real cloud login and lifts the session cookie — padlock included.', portal_button='Sign In to View File',
  portal_url='https://dropbox.com.file-sync-secure.net'),
 'COURSE-39-COLLAB-INVITES': dict(sim_type='email', sim_label='Slack / Teams / Zoom Invite Trap Simulator',
  sender_name='Slack', sender_email='no-reply@slack-team-invite.net', return_path='bounce@collab-blast-4.io',
  subject='You have been added to workspace "URGENT-PAYROLL-REVIEW"',
  headline='Join your team workspace to review the payroll correction',
  body='Your colleagues are discussing a payroll correction that affects your department. Join the workspace with your corporate email to participate.',
  button_text='Join Workspace', hover_url='https://slack.com.workspace-join-urgent.net'),
 'COURSE-40-SAFE-DOC-VERIFICATION': dict(sim_type='ir', sim_label='Unknown File Validation Protocol Simulator',
  ir_steps=[
   dict(title='Confirm Expectation', detail='Ask yourself: did I request this exact file from this exact sender?'),
   dict(title='Sandbox First', detail='Upload to the enterprise sandbox or detonation service before opening.'),
   dict(title='Verify Out-of-Band', detail='Confirm via a known phone number or internal chat, never the email\'s reply chain.'),
   dict(title='Report Anomalies', detail='Anything demanding macros or "Enable Content" goes to SOC immediately.')]),
}
